Repository NSWSESMembers/availability-poc, pull requests merged in 2018-05, with the labels that each got.

#325 Refactor capabilities into tags
  client/src/graphql/all-groups.query.js
  client/src/graphql/create-group.mutation.js
  client/src/graphql/current-user.query.js
  client/src/graphql/groups-users.query.js
  client/src/graphql/join-group.mutation.js
  client/src/graphql/organisation-tags.query.js
  client/src/graphql/search-group.query.js
  client/src/screens/groups/NewGroup.js
  server/src/__tests__/creators.js
  server/src/creators.js
  server/src/logic.js
  server/src/models-mock.js
  server/src/models.js
  server/src/schema.js
  server/src/test-data/fixtures.js
  server/src/test-data/load.js
  server/tests/current-user.test.js
Labels: enhancement, refactor

#320 Group Details Page Rewrite
  client/src/components/Users/UserListItem.js
  client/src/components/Users/__tests__/UserListItem.js
  client/src/components/Users/__tests__/__snapshots__/UserListItem.js.snap
  client/src/components/Users/index.js
  client/src/components/Users/styles.js
  client/src/graphql/join-group.mutation.js
  client/src/screens/groups/GroupDetails.js
  client/src/screens/groups/components/GroupDetailsHeader.js
  client/src/screens/groups/components/GroupDetailsList.js
  client/src/screens/groups/components/IconButton.js
  client/src/screens/groups/components/__tests__/GroupDetailsHeader.js
  client/src/screens/groups/components/__tests__/GroupDetailsList.js
  client/src/screens/groups/components/__tests__/IconButton.js
  client/src/screens/groups/components/__tests__/__snapshots__/GroupDetailsHeader.js.snap
  client/src/screens/groups/components/__tests__/__snapshots__/GroupDetailsList.js.snap
  client/src/screens/groups/components/__tests__/__snapshots__/IconButton.js.snap
  client/src/screens/groups/components/styles.js
  client/src/screens/groups/styles.js
Labels: design, refactor

#336 Skip gathering/printing test coverage for default `yarn test`
  client/package.json
  server/package.json
Labels: unittest

#342 Add apns-test script for sending test pushes to APNS
  server/.gitignore
  server/package.json
  server/scripts/apns.js
  server/src/push/apns.js
  server/yarn.lock
Labels: enhancement

#367 toast for copied to clipboard action on internal params screen
  client/src/screens/burger/components/ParamsListItem.js
Labels: verify-ios
