Repository NSWSESMembers/availability-poc, pull requests merged in 2018-04, with the labels that each got.

#252 Make web build and cache better, CDN safe
  web/.gitignore
  web/dist/.gitignore
  web/package.json
  web/public/index.html
  web/server/server.js
  web/static/favicon.png
  web/template.html
  web/webpack.config.js
  web/yarn.lock
Labels: infrastructure, web

#254 Event Response Modals refactor
  client/src/components/Modal/ListModal.js
  client/src/components/Modal/NumberInputModal.js
  client/src/screens/events/Response.js
Labels: enhancement, refactor

#268 changed group sort order and changed fixture creation order
  server/src/logic.js
  server/src/test-data/fixtures.js
Labels: refactor

#267 Added loading state to create group page
  client/src/screens/groups/NewGroup.js
Labels: enhancement

#275 Make Monday start at 0 minutes 0 seconds
  server/src/test-data/fixtures.js
Labels: data

#276 make the start time match the written description
  server/src/test-data/fixtures.js
Labels: data

#273 dropped the AM/PM from the display of times that are in 24hr
  client/src/components/DateTime/TimeSelect.js
Labels: design

#271 optimisticResponse for createTimeSegment
  client/src/screens/schedules/Detail.js
Labels: apollo, enhancement

#272 strike through the text of days that are out of range
  client/src/components/DateTime/styles.js
Labels: design

#274 Tweaked the words used on the default time segments
  client/src/screens/schedules/Detail.js
Labels: design

#300 Fix bug occurring when there are no events on home
  client/src/screens/events/Root.js
  client/src/screens/groups/Root.js
  client/src/screens/home/Root.js
Labels: bug, bugsnag

#314 Collect coverage from all files (even untested)
  client/package.json
  server/package.json
Labels: unittest

#313 More client test coverage
  client/src/components/Alert/__tests__/Alert.js
  client/src/components/Alert/__tests__/__snapshots__/Alert.js.snap
  client/src/components/Button/Button.js
  client/src/components/Button/ButtonBox.js
  client/src/components/Button/ButtonIcon.js
  client/src/components/Button/ButtonNavBar.js
  client/src/components/Button/ButtonRow.js
  client/src/components/Button/__tests__/Button.js
  client/src/components/Button/__tests__/ButtonBox.js
  client/src/components/Button/__tests__/ButtonIcon.js
  client/src/components/Button/__tests__/ButtonNavBar.js
  client/src/components/Button/__tests__/ButtonRow.js
  client/src/components/Button/__tests__/ButtonText.js
  client/src/components/Button/__tests__/__snapshots__/Button.js.snap
  client/src/components/Button/__tests__/__snapshots__/ButtonBox.js.snap
  client/src/components/Button/__tests__/__snapshots__/ButtonIcon.js.snap
  client/src/components/Button/__tests__/__snapshots__/ButtonNavBar.js.snap
  client/src/components/Button/__tests__/__snapshots__/ButtonRow.js.snap
  client/src/components/Button/__tests__/__snapshots__/ButtonText.js.snap
  client/src/components/ButtonRowPicker/__tests__/ButtonRowPicker.js
  client/src/components/ButtonRowPicker/__tests__/__snapshots__/ButtonRowPicker.js.snap
  client/src/components/Container/Center.js
  client/src/components/Container/Footer.js
  client/src/components/Container/Half.js
  client/src/components/Container/Holder.js
  client/src/components/Container/__tests__/Center.js
  client/src/components/Container/__tests__/Container.js
  client/src/components/Container/__tests__/Footer.js
  client/src/components/Container/__tests__/Half.js
  client/src/components/Container/__tests__/Holder.js
  client/src/components/Container/__tests__/__snapshots__/Center.js.snap
  client/src/components/Container/__tests__/__snapshots__/Container.js.snap
  client/src/components/Container/__tests__/__snapshots__/Footer.js.snap
  client/src/components/Container/__tests__/__snapshots__/Half.js.snap
  client/src/components/Container/__tests__/__snapshots__/Holder.js.snap
  client/src/components/Icon/__tests__/__snapshots__/index.js.snap
  client/src/components/Icon/__tests__/index.js
  client/src/components/Input/__tests__/Input.js
  client/src/components/Input/__tests__/__snapshots__/Input.js.snap
  client/src/components/MapMarker/__tests__/UserMarker.js
  client/src/components/MapMarker/__tests__/__snapshots__/UserMarker.js.snap
  client/src/components/Paper/__tests__/Paper.js
  client/src/components/Paper/__tests__/__snapshots__/Paper.js.snap
  client/src/components/Progress/__tests__/Progress.js
  client/src/components/Progress/__tests__/__snapshots__/Progress.js.snap
Labels: unittest

#317 Add codecov badges to READMEs
  README.md
  client/README.md
  server/README.md
Labels: non-tech, unittest

#323 Test for Segment component
  client/src/components/Segment/__tests__/Segment.js
  client/src/components/Segment/__tests__/__snapshots__/Segment.js.snap
Labels: unittest

#321 Tests for DateTime component
  client/src/components/DateTime/__tests__/DateRange.js
  client/src/components/DateTime/__tests__/DateSelect.js
  client/src/components/DateTime/__tests__/TimeSelect.js
  client/src/components/DateTime/__tests__/__snapshots__/DateRange.js.snap
  client/src/components/DateTime/__tests__/__snapshots__/DateSelect.js.snap
  client/src/components/DateTime/__tests__/__snapshots__/TimeSelect.js.snap
Labels: unittest

#322 Tests for Modal component
  client/src/components/Modal/__tests__/ListModal.js
  client/src/components/Modal/__tests__/Modal.js
  client/src/components/Modal/__tests__/NumberInputModal.js
  client/src/components/Modal/__tests__/TextInputModal.js
  client/src/components/Modal/__tests__/__snapshots__/ListModal.js.snap
  client/src/components/Modal/__tests__/__snapshots__/Modal.js.snap
  client/src/components/Modal/__tests__/__snapshots__/NumberInputModal.js.snap
  client/src/components/Modal/__tests__/__snapshots__/TextInputModal.js.snap
Labels: unittest
