Repository NSWSESMembers/availability-poc, pull requests merged in 2018-06, with the labels that each got.

#477 Group Screens for Web
  server/src/logic.js
  server/src/resolvers.js
  server/src/schema.js
  web/package.json
  web/src/app.js
  web/src/components/Alerts/Alert.js
  web/src/components/Alerts/Alert.styles.js
  web/src/components/DisplayRequests.js
  web/src/components/Messages/Message.js
  web/src/components/Selects/SelectOption.js
  web/src/components/Selects/Tag.js
  web/src/components/Selects/Tag.styles.js
  web/src/components/Tables/EnhancedTableHead.js
  web/src/constants.js
  web/src/graphql/create-group.mutation.js
  web/src/graphql/current-org.query.js
  web/src/graphql/current-user.query.js
  web/src/graphql/get-tags.query.js
  web/src/graphql/join-group.mutation.js
  web/src/graphql/leave-group.mutation.js
  web/src/graphql/update-group.mutation.js
  web/src/routers/AppRouter.js
  web/src/screens/partial/DisplayGroupsTable.js
  web/src/screens/private/Dashboard.js
  web/src/screens/private/Events/EditEvent.js
  web/src/screens/private/Events/EditEvent.styles.js
  web/src/screens/private/Events/ViewEvents.js
  web/src/screens/private/Events/ViewEvents.styles.js
  web/src/screens/private/Groups/EditGroup.js
  web/src/screens/private/Groups/EditGroup.styles.js
  web/src/screens/private/Groups/ViewGroups.js
  web/src/screens/private/Groups/ViewGroups.styles.js
  web/src/screens/private/Groups/components/GroupTable.js
  web/src/screens/private/Schedules/AddSchedule.js
  web/src/screens/private/Schedules/AddSchedule.styles.js
  web/src/screens/private/Schedules/ViewSchedules.js
  web/src/screens/private/Schedules/components/ScheduleTable.js
  web/src/selectors/groups.js
  web/src/styles/AppStyle.js
  web/yarn.lock
Labels: web

#493 Client - Change android launch mode
  client/android/app/src/main/AndroidManifest.xml
Labels: new shell needed

#476 Push Message Emitter
  server/src/callback.js
  server/src/logic.js
  server/src/main.js
  server/src/push/apns.js
  server/src/push/broker.js
  server/src/push/emitters.js
  server/src/push/fcm.js
  server/src/push/index.js
Labels: verify-ios

#515 Web Logo Updates
  web/src/app.js
  web/src/components/Panels/FormPanel.js
  web/src/components/Panels/FormPanel.styles.js
  web/src/screens/partial/Header.js
  web/src/screens/partial/Header.styles.js
  web/src/screens/private/Events/EditEvent.js
  web/src/screens/private/Groups/EditGroup.js
  web/src/screens/private/Schedules/AddSchedule.js
  web/src/screens/private/Schedules/EditSchedule.js
  web/src/screens/private/Schedules/components/ScheduleHeader.js
  web/src/styles/AppStyle.js
  web/static/logo.jpg
Labels: web

#507 Mobile Availability Improvements
  client/__tests__/selectors/schedules.test.js
  client/src/screens/schedules/Detail.js
  client/src/selectors/schedules.js
Labels: mobile
